version: "3"
services:
  mysql:
    container_name: anodoko-mysql
    build:
      context: ./db
      dockerfile: dev.M1.Dockerfile
    env_file: ./.env
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
    ports:
      - "7122:3306"
    networks:
      - anodoko

  phpmyadmin:
    container_name: anodoko-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 7123:80
    env_file: ./.env
    depends_on:
      - mysql
    networks:
      - anodoko

  api:
    container_name: anodoko-api
    build:
      context: ./api
      dockerfile: dev.M1.Dockerfile
    env_file: ./.env
    volumes:
      - ./api/:/app
    ports:
      - 7121:8080
    depends_on:
      - mysql
    networks:
      - anodoko

  client:
    container_name: anodoko-client
    build:
      context: ./client
      dockerfile: dev.M1.Dockerfile
    env_file: ./.env
    volumes:
      - ./client:/app
    ports:
      - "7120:3000"
    depends_on:
      - api
    networks:
      - anodoko
    tty: true

volumes:
  mysql:

networks:
  anodoko:
    driver: bridge
